### ISSUE TITLE
Failed to send feedback

### ISSUE THREAD

**Issue by kirs** [testmycode/tmc-cli#383]
Thank you so much for the Aalto-C summer course.

Here is the issue I get when trying to submit the feedback:

```
Submitting: Module_3-03_join
Test results: 1/1 tests passed
100%
All tests passed on server!
Points permanently awarded: [M3.03]
Send feedback for Module_3-03_join? [Y/n] y
Feedback question: How difficult was this exercise? (1: trivial -- 5: very difficult)
[0-5] 3
Feedback question: Did this exercise support your learning? (1: not at all -- 5: very much)
[0-5] 5
Command failed in tmc-core, check tmc-cli.log file for more info
Failed to send feedback.
```

Why does it fail and where can I find `tmc-cli.log`?

`TMC-CLI version 0.7.1`

@Salmela @jclc

**Comment by Salmela** [comment]
In linux the log file is at `/home/YOUR_USERNAME/.config/tmc-cli/logs/tmc-cli.log`.
In windows it's apparently in `Users\User\.config\logs`

I would really appreciate if you could post the log file. If the file is really long you can paste it in http://pastebin.com/ and just post a link to it.

And thanks for trying tmc-cli.

**Comment by kirs** [comment]
Thank you for information about the log.
Maybe it's a good idea to print full log path instead of `check tmc-cli.log`.

```
2016-07-14 19:42:26 INFO  TmcCore:109 - Creating new SendFeedback command
2016-07-14 19:42:26 INFO  HttpRequestExecutor:157 - Received http response with non 2xx response code 500 with body "org.apache.http.entity.BufferedHttpEntity@431cd9b2"
2016-07-14 19:42:26 ERROR TmcUtil:209 - Command failed in tmc-core
fi.helsinki.cs.tmc.core.exceptions.FailedHttpResponseException: Response code: 500
        at fi.helsinki.cs.tmc.core.communication.http.HttpRequestExecutor.handleResponse(HttpRequestExecutor.java:163)
        at fi.helsinki.cs.tmc.core.communication.http.HttpRequestExecutor.executeRequest(HttpRequestExecutor.java:142)
        at fi.helsinki.cs.tmc.core.communication.http.HttpRequestExecutor.call(HttpRequestExecutor.java:84)
        at fi.helsinki.cs.tmc.core.communication.http.HttpTasks$2.call(HttpTasks.java:94)
        at fi.helsinki.cs.tmc.core.communication.http.HttpTasks$2.call(HttpTasks.java:91)
        at fi.helsinki.cs.tmc.core.communication.TmcServerCommunicationTaskFactory$7.call(TmcServerCommunicationTaskFactory.java:293)
        at fi.helsinki.cs.tmc.core.communication.TmcServerCommunicationTaskFactory$7.call(TmcServerCommunicationTaskFactory.java:289)
        at fi.helsinki.cs.tmc.core.commands.SendFeedback.call(SendFeedback.java:44)
        at fi.helsinki.cs.tmc.core.commands.SendFeedback.call(SendFeedback.java:16)
        at fi.helsinki.cs.tmc.cli.tmcstuff.TmcUtil.sendFeedback(TmcUtil.java:181)
        at fi.helsinki.cs.tmc.cli.tmcstuff.FeedbackHandler.sendFeedback(FeedbackHandler.java:38)
        at fi.helsinki.cs.tmc.cli.command.SubmitCommand.run(SubmitCommand.java:139)
        at fi.helsinki.cs.tmc.cli.command.core.AbstractCommand.execute(AbstractCommand.java:63)
        at fi.helsinki.cs.tmc.cli.Application.runCommand(Application.java:67)
        at fi.helsinki.cs.tmc.cli.Application.run(Application.java:132)
        at fi.helsinki.cs.tmc.cli.Application.main(Application.java:141)
2016-07-14 19:42:26 ERROR TmcUtil:185 - Couldn't send feedback
fi.helsinki.cs.tmc.core.exceptions.FailedHttpResponseException: Response code: 500
        at fi.helsinki.cs.tmc.core.communication.http.HttpRequestExecutor.handleResponse(HttpRequestExecutor.java:163)
        at fi.helsinki.cs.tmc.core.communication.http.HttpRequestExecutor.executeRequest(HttpRequestExecutor.java:142)
        at fi.helsinki.cs.tmc.core.communication.http.HttpRequestExecutor.call(HttpRequestExecutor.java:84)
        at fi.helsinki.cs.tmc.core.communication.http.HttpTasks$2.call(HttpTasks.java:94)
        at fi.helsinki.cs.tmc.core.communication.http.HttpTasks$2.call(HttpTasks.java:91)
        at fi.helsinki.cs.tmc.core.communication.TmcServerCommunicationTaskFactory$7.call(TmcServerCommunicationTaskFactory.java:293)
        at fi.helsinki.cs.tmc.core.communication.TmcServerCommunicationTaskFactory$7.call(TmcServerCommunicationTaskFactory.java:289)
        at fi.helsinki.cs.tmc.core.commands.SendFeedback.call(SendFeedback.java:44)
        at fi.helsinki.cs.tmc.core.commands.SendFeedback.call(SendFeedback.java:16)
        at fi.helsinki.cs.tmc.cli.tmcstuff.TmcUtil.sendFeedback(TmcUtil.java:181)
        at fi.helsinki.cs.tmc.cli.tmcstuff.FeedbackHandler.sendFeedback(FeedbackHandler.java:38)
        at fi.helsinki.cs.tmc.cli.command.SubmitCommand.run(SubmitCommand.java:139)
        at fi.helsinki.cs.tmc.cli.command.core.AbstractCommand.execute(AbstractCommand.java:63)
        at fi.helsinki.cs.tmc.cli.Application.runCommand(Application.java:67)
        at fi.helsinki.cs.tmc.cli.Application.run(Application.java:132)
        at fi.helsinki.cs.tmc.cli.Application.main(Application.java:141)
```

**Comment by Salmela** [comment]
I have never seen that error code and the problem doesn't seem to be in tmc-cli, but in tmc-server.

I made new issue about the log file path at #384.

@jamox will propably look at the server issue at some point.

**Comment by jamo** [comment]
Thanks for reporting this, I'll check the logs in a few days, whenever I have proper internet access...

**Comment by kirs** [comment]
Kiitos paljon!
